name: CI


on:
  pull_request:
    branches:
      - master

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install modules
        run: npm ci

      - name: Check code quality
        uses: stefanoeb/eslint-action@1.0.2

      - name: Run tests
        run: npm run test
      
      - name: Browser Build
        run: npm run build-browser-sdk
        env:
          IFRAME_SECURE_ORGIN: ${{ secrets.IFRAME_SECURE_ORGIN }}
          IFRAME_SECURE_SITE: ${{ secrets.IFRAME_SECURE_SITE }}

      - name: Build iFrame
        run: npm run build-iframe
        env:
          IFRAME_SECURE_ORGIN: ${{ secrets.IFRAME_SECURE_ORGIN }}
          IFRAME_SECURE_SITE: ${{ secrets.IFRAME_SECURE_SITE }}

      - name: Build Node SDK
        env:
          IFRAME_SECURE_ORGIN: ${{ secrets.IFRAME_SECURE_ORGIN }}
          IFRAME_SECURE_SITE: ${{ secrets.IFRAME_SECURE_SITE }}
        run: |
          npm run build:types 
          npm run build-node-sdk

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
    defaults:
      run:
        working-directory: ./
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          path: ./  

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1